# Generated by Django 5.2.6 on 2025-10-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='task',
            name='funding_scoped',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.CreateModel(
            name='TaskScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_scoped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_scopes', to='api.funding')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_scopes', to='api.project')),
                ('project_funding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_scopes', to='api.projectfunding')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='api.task')),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='api_tasksco_project_232fb5_idx'), models.Index(fields=['funding'], name='api_tasksco_funding_60e891_idx'), models.Index(fields=['project_funding'], name='api_tasksco_project_39ffb7_idx'), models.Index(fields=['funding_scoped'], name='api_tasksco_funding_b8c7ad_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('funding__isnull', True), ('project_funding__isnull', True)), models.Q(('project__isnull', True), ('funding__isnull', False), ('project_funding__isnull', True)), models.Q(('project__isnull', True), ('funding__isnull', True), ('project_funding__isnull', False)), _connector='OR'), name='taskscope_exactly_one')],
            },
        ),
    ]
