# Generated by Django 5.2.6 on 2025-09-18 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('grant', 'Grant'), ('sponsorship', 'Sponsoring'), ('donation', 'Darowizna'), ('internal', 'Wewnętrzne')], default='internal', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('agreement_number', models.CharField(blank=True, max_length=100)),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reporting_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='funding_dates_ok')],
            },
        ),
        migrations.CreateModel(
            name='FundingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_status', models.CharField(choices=[('todo', 'To do'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=10)),
                ('default_priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('default_est_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('default_due_days', models.IntegerField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_blueprint', to='api.funding')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('closed', 'Closed')], default='new', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_start', models.DateField(blank=True, null=True)),
                ('allocation_end', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_projects', to='api.funding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_fundings', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='fundings',
            field=models.ManyToManyField(blank=True, related_name='projects', through='api.ProjectFunding', to='api.funding'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_scoped', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=10)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_currency', models.CharField(default='PLN', max_length=3)),
                ('receipt_url', models.URLField(blank=True)),
                ('receipt_note', models.TextField(blank=True)),
                ('est_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('funding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.funding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='api.fundingtask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectfunding',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_start__isnull', True), ('allocation_end__isnull', True), ('allocation_start__lte', models.F('allocation_end')), _connector='OR'), name='projectfunding_dates_ok'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfunding',
            unique_together={('project', 'funding')},
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='project_dates_ok'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('due_date__isnull', True), ('start_date__lte', models.F('due_date')), _connector='OR'), name='task_dates_ok'),
        ),
    ]
