# Generated by Django 5.2.6 on 2025-09-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='founder',
            new_name='funder',
        ),
    ]
